# Generated by Django 3.0.7 on 2020-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeetingId', models.CharField(max_length=100)),
                ('MeetingName', models.CharField(max_length=100)),
                ('CreateTime', models.DateTimeField(null=True)),
                ('UserId', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
